version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret

  test:
    build:
      context: .
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: secret
    volumes:
      - ./scripts:/var/opt/psql/scripts.d
    links:
      - db
    depends_on:
      - db
